FROM node:latest

LABEL author="TestFile"

ENV NODE_value=Production
ENV PORT=3000


COPY . /var/www
WORKDIR /var/www

VOLUME [ "/var/www" ]

RUN npm install

EXPOSE 3000

EXPOSE $PORT

ENTRYPOINT [ "npm","start" ]